### PR TITLE
more efficient base image

### PR DESCRIPTION
**Pull request by bwoodhouse322**

### CODE REVIEW

**Comment by radu-matei** [comment]
Hey, @bwoodhouse322 and thanks for this!

Have you actually tested this with a few types of apps? I assume that, at least for web applications, `alpine` needs at least to install the certificates - this is part of the reason `ubuntu` was the base image before.

```
RUN apk add --no-cache ca-certificates && update-ca-certificates
```

**Comment by bwoodhouse322** [comment]
Hey @radu-matei  This isn't tested, but you are absolutely right the ca-certs must and have been added. Could you quickly test? I don't have Minikube set up on my current machine, but will test tomorrow if not possible, Thanks!

**Comment by bwoodhouse322** [comment]
https://github.com/iron-io/dockers/tree/master/go  the iron/go image is production ready I believe i.e niggles like ca-certs have been addressed already. Maybe this may make a more suitable base image

**Comment by bwoodhouse322** [comment]
OK silly me I can tests this just with docker, can I use the app that you used in your screenshot? just to compare the change?

**Comment by radu-matei** [comment]
Sure, go ahead and use it!

**Comment by bwoodhouse322** [comment]
is it on your Github? I can only see the Docker image name, not the app name  :stuck_out_tongue_winking_eye:

**Comment by radu-matei** [comment]
Yeah, it is actually in this repo - https://github.com/metaparticle-io/package/blob/master/go/examples/web-aci/main.go

**Comment by bwoodhouse322** [comment]
Updated and tested with the example above, comes out at 6mb! https://hub.docker.com/r/bwoodhouse322/go-test/tags/ Thanks @radu-matei !

**Comment by bwoodhouse322** [comment]
@brendandburns Are you still active on this project? Just wanted to make you aware of this PR if interested, thanks!

**Comment by brendandburns** [comment]
Sorry for the delay, vacations etc. definitely still active.

This LGTM.

**Pull request merged**
