### PR TITLE
test: add first tests when testing for env variable

### PR DESCRIPTION
**Pull request by pfongkye**
Still need to add tests for options argument

### CODE REVIEW

**Comment by pfongkye** [comment]
@brendanburns can you confirm me that it should be `options.dockerfile` instead of `src` when looking at [code pointer](https://github.com/metaparticle-io/package/blob/686bc97b31b60fa3afeae1bb73d2506e4c651650/javascript/metaparticle-package/index.js#L31)?

**Comment by brendandburns** [comment]
Yes, that's correct.  Thanks for catching that bug!

**Comment by brendandburns** [comment]
@pfongkye LGTM, but did you fix that dockerfile bug you found?

**Comment by pfongkye** [comment]
@brendanburns I created a separate PR: https://github.com/metaparticle-io/package/pull/61

**Comment by brendandburns** [comment]
LGTM, thanks!

**Pull request merged**
