### PR TITLE
fix issue #9, adding exception handling for it to work on MacOS

### PR DESCRIPTION
**Pull request by chanezon**
Signed-off-by: Patrick Chanezon <patlist@chanezon.com>

### CODE REVIEW

**Comment by christopherhein** [comment]
I've got a different approach not sure if it's better or not… thoughts?

```node
    var os = require('os');

    inDocker = () => {
        if (os.platform() === 'darwin') {
          return false;
        }
        if (process.env.METAPARTICLE_IN_CONTAINER === "true") {
            return true;
        }
        var info = fs.readFileSync("/proc/1/cgroup");
        // This is a little approximate...
        if (info.indexOf("docker") != -1) {
            return true;
        }
        if (info.indexOf("kubepods") != -1) {
            return true;
        }
        return false;
    };
```

**Comment by chanezon** [comment]
Hmmm, with this test I guess you'll have the same issue with Docker for Windows:-)

**Comment by christopherhein** [comment]
Oh, great point! Alright, I'll switch my local code to yours.

**Comment by stealthybox** [comment]
:+1: @chanezon
I did the same thing

**Comment by brendandburns** [comment]
Thanks!

**Pull request merged**
