### PR TITLE
Make metaparticle a python package for portability

### PR DESCRIPTION
**Pull request by wagoodman**
This is simply packaging up what code was already there into a standard python package (#28). I tried to leave the existing functionality and example working as is, though there were a few deviations, the most notable changes are:

- the `Containerize` decorator is capitalized
- the `options` dictionary has been broken out into `runtime` and `package` options similar to other language implementations 

This introduces a few things:

- Tox + pytest have been established for running tests (no real tests written yet, but the framework to run tests has been done: `make test`)
- Version kept in the metaparticle/version.py (starting at 0.0.1)
- added initial option validation (and now options are named tuples)
- currently supports python2 and python3
- bootstraps your local dev environment: `make venv`

Let me know what you think.

### CODE REVIEW

**Comment by wagoodman** [comment]
I noticed the chatter on #35... @vbmade2000 does this help lay a framework to fit your tests into?

@brendandburns I just noticed you put in a very similar PR just now... should I close this one? or do we want to combine these at all?

**Comment by vbmade2000** [comment]
@wagoodman I was almost done with tests using Python built in unit test package. You can push code. I need to modify my tests significantly but I am fine with it/ The only concern is I am not using tox or pyunit.

**Comment by vbmade2000** [comment]
I think I should proceed further after merging of this branch to accommodate new changes.

**Comment by brendandburns** [comment]
@wagoodman I'm going to merge your PR first, and then adapt #43 to work with the stuff you did in this PR. But that probably means pausing further work until both #43 and #44 are merged...

Does that work for you?

**Comment by wagoodman** [comment]
@brendandburns works great! Agreed with pausing on further python work... PRs accidentally were getting a bit crowded.

**Pull request merged**
